Restaurant/Models/Cuisine.cs
using System.Collections.Generic;

namespace Restaurant.Models
{
    public class Cuisine
    {
        public int CuisineId {get;set;}
        public string Name {get; set;}
        public virtual ICollection<RestaurantV> RestaurantVariable {get;set;}

        public Cuisine()
        {
            this.RestaurantVariable = new HashSet<RestaurantV>();
        }
    }
}

Restaurant/Models/CuisineContext.cs
using Microsoft.EntityFrameworkCore;

namespace Restaurant.Models
{
  public class CuisineContext : DbContext
  {
    public virtual DbSet<Cuisine> Cuisines {get;set;}
    public DbSet<RestaurantV> Restaurants { get; set; }

    public CuisineContext(DbContextOptions options) : base(options) { }
  }
}

Restaurant/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Restaurant.Models
{
  public class CuisineContextFactory : IDesignTimeDbContextFactory<CuisineContext>
  {

    CuisineContext IDesignTimeDbContextFactory<CuisineContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<CuisineContext>();
      var connectionString = configuration.GetConnectionString("DefaultConnection");

      builder.UseMySql(connectionString);

      return new CuisineContext(builder.Options);
    }
  }
}

Restaurant/Models/ErrorViewModel.cs
using System;

namespace Restaurant.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Restaurant/Models/Restaurant.cs
using System.Collections.Generic;
using MySql.Data.MySqlClient;

namespace Restaurant.Models
{
    public class RestaurantV
    {
        
        public int RestaurantVId {get;set;}
        public int CuisineId { get; set;}
        public string Hours { get; set; }
        public int Price { get; set; }
        public string Location {get; set;}
        public string Name {get;set;}
     
        public virtual Cuisine Cuisine {get;set;}
    }
}

Restaurant/Controllers/CuisineController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurant.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System;

namespace Restaurant.Controllers
{
    public class CuisineController : Controller
    {
        private readonly CuisineContext _db;
        public CuisineController(CuisineContext db)
        {
            _db = db;
        }
        public ActionResult Index()
        {
            List<Cuisine> model = _db.Cuisines.Include(cuisine => cuisine.RestaurantVariable).ToList();
            
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Cuisine category)
        {
            _db.Cuisines.Add(category);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
           ViewBag.Name = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
            List<RestaurantV> thisCuisine = new List<RestaurantV>{};
            foreach(RestaurantV way in _db.Restaurants)
            {
                if(id == way.CuisineId)
                {
                    thisCuisine.Add(way);
                }
            }
            return View(thisCuisine);
        }
        public ActionResult Edit(int id)
        {
            var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
            return View(thisCuisine);
        }
        [HttpPost]
        public ActionResult Edit(Cuisine category)
        {
            _db.Entry(category).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            var thisCuisine = _db.Cuisines.FirstOrDefault(Cuisine => Cuisine.CuisineId == id);
            return View(thisCuisine);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
            _db.Cuisines.Remove(thisCuisine);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Restaurant/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Restaurant.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

  }
}

Restaurant/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurant.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace Restaurant.Controllers
{
    public class RestaurantController : Controller
    {
        private readonly CuisineContext _db;

        public RestaurantController(CuisineContext db)
        {
            _db = db;
        }
        public ActionResult Index()
        {
            List<RestaurantV> model = _db.Restaurants.Include(restaurants => restaurants.Cuisine).ToList();
            return View(model);
        }
        public ActionResult Create()
        {
            ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
            return View();
        }
        [HttpPost]
        public ActionResult Create(RestaurantV restaurant)
        {
            _db.Restaurants.Add(restaurant);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int idR)
        {
            RestaurantV thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantVId == idR);
        
            return View(thisRestaurant);
        }
        [HttpGet]
        public ActionResult Edit(int idR)
        {
            Console.WriteLine(idR);
            RestaurantV thisRestaurant = _db.Restaurants.FirstOrDefault(rest => rest.RestaurantVId == idR);
            Console.WriteLine(thisRestaurant.Name);
            ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
            return View(thisRestaurant);
            
        }
        [HttpPost, ActionName("Edit")]
        public ActionResult Edit(RestaurantV restaurant)
        {
            // _db.Update(restaurant);
            Console.WriteLine(restaurant.CuisineId);
            Console.WriteLine(restaurant.RestaurantVId);
            _db.Entry(restaurant).State = EntityState.Modified;
            
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet("/Cuisine/Details/{id}/deleteconfirmed")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantVId == id);
            _db.Restaurants.Remove(thisRestaurant);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Restaurant/Views/Cuisine/Create.cshtml
@{
  Layout = "_Layout";
}
@model Restaurant.Models.Cuisine

@using (Html.BeginForm())
{
    @Html.TextBoxFor(model => model.Name, new {@placeholder="enter cuisine name"})
    <input class="btn btn-danger" type="submit" value="Add new cuisine" />
}
<p>@Html.ActionLink("Show all cuisines", "Index")</p>

Restaurant/Views/Cuisine/Details.cshtml
@{
  Layout = "_Layout";
}
@model List<Restaurant.Models.RestaurantV>
@using Restaurant.Models;

<h1>Here are all the @ViewBag.Name.Name restaurants:</h1>

@foreach(var whatever in @Model)
{
   <ul>
    <li>@Html.ActionLink($"{whatever.Name}", "Details","Restaurant",  new { idR = whatever.RestaurantVId}, new { idC = whatever.CuisineId} ) </li>
    </ul>
}

Restaurant/Views/Cuisine/Index.cshtml
@{
  Layout = "_Layout";
}
@using Restaurant.Models;

@if(@Model.Count == 0)
{
    <p>@Html.ActionLink("Add new Cuisine", "Create")</p>
}

@foreach(Cuisine cuisineV in Model)
{
    <div class="allOutline">
    <h2>@Html.ActionLink($"{cuisineV.Name} restaurants", "Details", new {id = cuisineV.CuisineId}) </h2>
    
@foreach(var item in cuisineV.RestaurantVariable)
   {
      
       <ul>
        <li><u>@item.Name</u></li>
       </ul>
      
   } 
   </div>
    
}

<p>@Html.ActionLink("Add new cuisine", "Create")</p>
<p>@Html.ActionLink("Add new restaurant", "Create")</p>

Restaurant/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1>Welcome, lets see what your favorite Restaraunt is?</h1>
</div>
<h2>@Html.ActionLink("Go To List of Cuisines", "Index", "Cuisine")</h2>

<p>@Html.ActionLink("Create Restaraunt", "Create", "Restaurant")</p>
<p>@Html.ActionLink("Add new cuisine", "Create", "Cuisine")</p>

Restaurant/Views/Restaurant/Create.cshtml
@{
  Layout = "_Layout";
}
@model Restaurant.Models.RestaurantV

<h1>Add a new Restaurant</h1>
@using (Html.BeginForm())
{
  <div class="form-group">
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })

    @Html.LabelFor(model => model.Hours)
    @Html.TextBoxFor(model => model.Hours, new { @class = "form-control" })

    @Html.LabelFor(model => model.Price)
    @Html.TextBoxFor(model => model.Price, new { @class = "form-control" })

    @Html.LabelFor(model => model.Location)
    @Html.TextBoxFor(model => model.Location, new { @class = "form-control" })

    @Html.LabelFor(model => model.Cuisine)
    @Html.DropDownList("CuisineId")
    
  </div>
  <input class="btn btn-danger"type="submit" value="Add new restaurant" />
}

Restaurant/Views/Restaurant/Details.cshtml
@{
  Layout = "_Layout";
}
@model Restaurant.Models.RestaurantV

<h1>Restaurant details for @Model.Name</h1>

<div class="row">
  <div class="card w-50">
  
    &nbsp
  </div>
  <div class="card w-50">
  
    <p>Hours: @Model.Hours</p>
    <p>Cost: @Model.Price</p>
    <p>Location: @Model.Location</p>
  </div>
</div>


<p>@Html.ActionLink("Add new restaurant", "Create")</p>
 <p><a href="/Cuisine/Details/@Model.RestaurantVId/deleteconfirmed"> Delete</a></p>
 <p>@Html.ActionLink("Edit", "Edit", "Restaurant", new {idR = @Model.RestaurantVId})</p>

Restaurant/Views/Restaurant/Edit.cshtml
@{
  Layout = "_Layout";
}
@model Restaurant.Models.RestaurantV

<h4>Edit a new Restaurant</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)

    @Html.LabelFor(model => model.Hours)
    @Html.TextBoxFor(model => model.Hours)

    @Html.LabelFor(model => model.Price)
    @Html.TextBoxFor(model => model.Price)

    @Html.LabelFor(model => model.Location)
    @Html.TextBoxFor(model => model.Location)

    @Html.LabelFor(model => model.CuisineId)
    @Html.DropDownList("CuisineId")

    @Html.HiddenFor(model => model.RestaurantVId)
    <input type="submit" value="Edit restaurant"/>
}
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Restaurant/Views/Restaurant/Index.cshtml
@{
  Layout = "_Layout";
}
@using Restaurant.Models;
@model List<Restaurant.Models.RestaurantV>;

<h1>Restaurants</h1>

@if(@Model.Count == 0)
{
    <h3> No Restaurants have been added yet which shoud. never be the case</h3>
}
@foreach(RestaurantV restrauntvv in Model)
{
  <ul>
    <li>@Html.ActionLink($"{restrauntvv.Name}", "Details", new { idR = restrauntvv.RestaurantVId}) | @restrauntvv.Cuisine.Name </li>
  </ul>
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>

Restaurant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link href="https://fonts.googleapis.com/css?family=Permanent+Marker|Raleway&display=swap" rel="stylesheet">
    <title>@ViewData["Title"] - Restaurant</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        
        <nav id="header" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
              <p id="navbar">@Html.ActionLink("Restaurant", "Index", "Restaurant")</p>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <p id="navbar">@Html.ActionLink("Home", "Index", "Home")</p>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Restaurant - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>